### ISSUE TITLE
POD5 squiggle files

### ISSUE THREAD

**Issue by lucilaviappiani** [shimlab/NanoSplicer#14]
Hi,

I’m working with POD5 files and I was wondering if it's possible to use them instead of FAST5 files for squiggle extraction and analysis in this project. If not, are there any plans to support POD5 in the future? Any guidance on how to proceed would be greatly appreciated.

Thanks in advance!

**Comment by youyupei** [comment]
Hi @lucilaviappiani

Thank you for reaching out! We’re currently working on supporting POD5 files for squiggle extraction and analysis, but it’s not fully supported yet.  We’ll keep this issue open and  updated on future developments.
