### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by prm123342** [shimlab/NanoSplicer#2]
Hi there, 

I have already tried reducing the chromosome size to reduce computations, but seems I can only get this error. 
When attempting to just run the example code I keep getting this error code at the first step:

python3 JWR_checker.py –-chrID=chr1 –-genome-loc=5296679-5296680  --output_csv input.bam example.h5
Traceback (most recent call last):
  File "JWR_checker.py", line 282, in <module>
    main()
  File "JWR_checker.py", line 251, in main
    param = JWR_checker_param()
  File "JWR_checker.py", line 193, in __init__
    self.bamfile, self.outfile = args            
ValueError: too many values to unpack (expected 2)

Any advice would be greatly appreciated.

**Comment by youyupei** [comment]
Hi there, 

I think the problem comes because the fisit "–" in "–-chrID"  and "–-genome-loc" doesn't seem correct. Let's try the updated code: `python3 JWR_checker.py --chrID=chr1 --genome-loc=5296679-5296680 --output_csv input.bam example.h5`
