### ISSUE TITLE
'Error in reverse_complement!!Bad bases in the seq.' and no bed output

### ISSUE THREAD

**Issue by MSajek** [shimlab/NanoSplicer#3]
Hi,
I run NanoSplicer on direct RNA sequencing and I see the following error during NanoSplicer.py step: 'Error in reverse_complement!!Bad bases in the seq error'. Is it because of direct RNA seq and not cDNA/DNA seq? Additional issue - as an output I have only tsv file, no bed file. It also looks like -o switch do not add the prefix to the output file, because always default name (output_prob_table.tsv) is used. Thanks in advance for any advice.

**Comment by youyupei** [comment]
Hi, 

Current version of NanoSplicer only works on cDNA. In dRNA sequencing the variation in dwell time is much larger, that is, the amount of time each nucleotide takes to go through the pore is much more variable.  This will require developing/testing a new dRNA specific version of NanoSplicer.

Also for the other issue you have mentioned, I would suggest to try with the most up-to-date script (use `git pull`). Feel free to let me know if the problem persist.
