### ISSUE TITLE
Regarding JWR_checker.py

### ISSUE THREAD

**Issue by Proy321** [shimlab/NanoSplicer#8]
Hi,

![1](https://github.com/shimlab/NanoSplicer/assets/140142819/c3810ac5-1c6c-4f6e-b3e9-5f74ccdaae36)
I was trying to execute the command python3 JWR_checker.py --chrID=chr1 --genome-loc=5296679-5297165 --output_csv input.bam example.h5 but it gave the following errors. It would be nice if you can assist me with the same.

Thanks

**Comment by youyupei** [comment]
Hi @Proy321，

Sorry for the late reply. I think the problem was the `--output_csv` argument. It shouldn't take any value. It was just a switch to indicate whether or not to output a CSV file.

Regards,
Yupei
