### ISSUE TITLE
ValueError: No objects to concatenate

### ISSUE THREAD

**Issue by gsukrit** [shimlab/NanoSplicer#9]
Hi team, 

Upon running the JWR_checker.py command on my bam file aligned with the genome reference, I get the following error (screenshot attached). Does this mean my bam file does not have any splice junctions detected to proceed further?

![image](https://github.com/shimlab/NanoSplicer/assets/81628564/253b625a-184f-4803-a0df-31a3890d38db)

**Comment by youyupei** [comment]
Hi @gsukrit, you are right. This is a known error when there is not junction detected in any read (Also see #7 ). I would recommend to check the mapping setting to make sure the mapper was set to a "splice-aware" mode.
